# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_rbf_kernel <- function(x1, x2, gamma) {
    .Call(`_manysvms_cpp_rbf_kernel`, x1, x2, gamma)
}

