# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_clip_dcd_optimizer <- function(H, q, lb, ub, eps, max_steps) {
    .Call(`_manysvms_cpp_clip_dcd_optimizer`, H, q, lb, ub, eps, max_steps)
}

cpp_rbf_kernel <- function(x1, x2, gamma) {
    .Call(`_manysvms_cpp_rbf_kernel`, x1, x2, gamma)
}

cpp_poly_kernel <- function(x1, x2, gamma, degree, coef0) {
    .Call(`_manysvms_cpp_poly_kernel`, x1, x2, gamma, degree, coef0)
}

